# 端口
server:
  port: 80

# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yihan?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: yihan

#sql打印
logging:
  level:
    com.lp.yihan.dao: DEBUG  #控制台SQL打印

# mybatis
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true  #开启驼峰规则
    call-setters-on-nulls: true
  mapper-locations: classpath:dao/*.xml  #xml配置